language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: p/0Z2eU3uy3Hqwb5odnmXRzavd3wodavvKumZtnp37Z868+/qes9B3jFRFBD1kPTRy9/UJltYePw1MPGmzcZsuoajlaFp/PtYXPt/GusvUXDyeuHtUJDDJafIYZWtp7RKcUGE8DwUEhrf5Fsd80Cbh8msb8t8/uaVRYG8q7FfXqmQXVhqNZd/6Mf8fgu+jOJ3zmJFCCHinOiAqCHQDR13+ed1ABLAK3/4c8u2mgQOX9urIi9+lUaRZ+YU/h0gb1qZaFRp1S8s6D5s+TgASa8U6nrzkiQ2x6mMSJN0qfLDZmMemW7NxYXYR0S/ll2NMnkjJzFeiXmasz3xz/jnCooXHa+fXhWzpjOCenElQuTb5QRPvRKO83ds/euo5jARZ9LXk/2FuZAKoE0xco+yTidWWgaUF9SwyWFAD0WZmFvleB4t52AwcVnCyxfXrZlzOeWZiBuQCZ2Wy2s41qM3lC1KoKg5e1fFOblYBSG50vP4NJh2oSbF544zdtrMzZIgcNU+sq6dVZji0tdjtOXNxnOMQrhSL8xnR7yHhiKTGekcUTXnxJO9XJMGiTNnta58vJmLAEc4d9UBQJhmk39lxUCtFQ8gpNPZ4nz+WUDW9wIy9Cu8vBg5++UITAWYviWSYbeBX6j53PaWMqvHersMEwKU2Rk3N1vMeca5VeRVKRoKYQ=
    - secure: wW+gCj5yUrq7fyp7nXWQZ/sg5rtf6LLFjuA0eTc4lygME4/ax0loGrnzicnnJpn/9RhzQgpe8Dc/71KoIgRZYYRWGlhnbmhPrAOz+tKYQoYsLzDilyyprYNAERF2yll3DXghpgjDspmcJWu9KctrIKR/CfTinSpanlfd/yEmuYZInNp7+fxyRelA2bXw/3G3Cw+yU0ecWRLtNK/YTlGbFc4s3NK47Vk6ay5NFCMQvp/ZokjaJUySSz410U4/i75MIQOln68ywZSGSnjYC6E2BWTAt3Ea1Lzah7bSYWjQjKwdnQ8B5n61+x8XgvOGv8WiodLXdy3Eqbzab2zrIx4/1snAYrYE+3ClTtO1GoUwQ1VJyq0wla1DqbQkKljlJRWOxKpnBmSjPdyZKaDkidekDTePr7HzCHj13jS1ioRtGymTCslItbgIGyHncGt6Vnl5PSr65Jh60LnlQrS/Js0mFFTNca8YeURWiUAhMCuoE2AO2JX0wdTDmBkcXaugvV8HMPVQnQ7wwKkaZBUIbZmXiHOSjC1cMsq6dbqDx3epQhLkSxY02xbe9cyg5TGIJNKYd98+pvxyPYpKkVVbvs31v7RdlqPFNO3fDqOcbG+Nksj4lvKTM8ODeax+SHUmDts6rfA5BGGAwjYVEFa/9ig3xJTwVeMVSKnhv+MHl/awilQ=

install:
   - npm install -g grunt-cli
   - npm -g install bower
   - npm install
   - bower install

script:
   - grunt jshint test:remote

